#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${1:?environment file is required}"
COMPOSE_FILE="$SCRIPT_DIR/docker-compose.prod.yml"
RUNTIME_ENV_FILE="$SCRIPT_DIR/.runtime.env"

env_value() {
  local file="${2:-$ENV_FILE}" name="$1" line value
  [[ -f "$file" ]] || return 0
  line="$(grep -E "^${name}=" "$file" | tail -n 1 || true)"
  value="${line#*=}"
  value="${value%\"}"
  value="${value#\"}"
  value="${value%\'}"
  value="${value#\'}"
  printf '%s' "$value"
}

desired_user="$(env_value POSTGRES_USER)"
desired_password="$(env_value POSTGRES_PASSWORD)"
desired_database="$(env_value POSTGRES_DB)"

if [[ -z "$desired_user" || -z "$desired_password" || -z "$desired_database" ]]; then
  echo "❌ PostgreSQL reconciliation requires POSTGRES_USER, POSTGRES_PASSWORD and POSTGRES_DB." >&2
  exit 1
fi

compose() {
  local env_args=(--env-file "$ENV_FILE")
  local backend_database_url
  if [[ -f "$RUNTIME_ENV_FILE" ]]; then
    env_args+=(--env-file "$RUNTIME_ENV_FILE")
    BACKEND_ENV_FILE="$ENV_FILE" docker compose "${env_args[@]}" -f "$COMPOSE_FILE" "$@"
  else
    backend_database_url="$(default_backend_database_url)"
    BACKEND_ENV_FILE="$ENV_FILE" BACKEND_DATABASE_URL="$backend_database_url" docker compose "${env_args[@]}" -f "$COMPOSE_FILE" "$@"
  fi
}

url_encode() {
  local raw="$1" encoded="" char hex i
  LC_ALL=C
  for ((i = 0; i < ${#raw}; i++)); do
    char="${raw:i:1}"
    case "$char" in
      [a-zA-Z0-9.~_-]) encoded+="$char" ;;
      *) printf -v hex '%%%02X' "'$char"; encoded+="$hex" ;;
    esac
  done
  printf '%s' "$encoded"
}

default_backend_database_url() {
  local user password database
  user="$(url_encode "$desired_user")"
  password="$(url_encode "$desired_password")"
  database="$(url_encode "$desired_database")"
  printf 'postgresql://%s:%s@z_postgres:5432/%s' "$user" "$password" "$database"
}

write_runtime_database_url() {
  local user="$1" password="$2" database="$3"
  local encoded_user encoded_password encoded_database
  encoded_user="$(url_encode "$user")"
  encoded_password="$(url_encode "$password")"
  encoded_database="$(url_encode "$database")"
  {
    echo "# Generated by deploy/reconcile-postgres.sh."
    echo "# Keeps the backend aligned with an existing PostgreSQL volume."
    echo "BACKEND_DATABASE_URL=postgresql://${encoded_user}:${encoded_password}@z_postgres:5432/${encoded_database}"
  } > "$RUNTIME_ENV_FILE"
  chmod 600 "$RUNTIME_ENV_FILE"
}

clear_runtime_database_url() {
  rm -f "$RUNTIME_ENV_FILE"
}

tcp_login_works() {
  local user="$1" password="$2" database="$3"
  compose exec -T \
    -e PGPASSWORD="$password" \
    z_postgres psql -h 127.0.0.1 -U "$user" -d "$database" -tAc 'SELECT 1' >/dev/null 2>&1
}

admin_user=""
admin_is_superuser=""
candidates=("$desired_user" z_user postgres)
legacy_file="$SCRIPT_DIR/.env.prod"
if [[ -f "$legacy_file" && "$legacy_file" != "$ENV_FILE" ]]; then
  legacy_user="$(env_value POSTGRES_USER "$legacy_file")"
  [[ -n "$legacy_user" ]] && candidates+=("$legacy_user")
fi

for candidate in "${candidates[@]}"; do
  [[ -z "$candidate" ]] && continue
  if compose exec -T -u postgres z_postgres psql -U "$candidate" -d postgres -tAc 'SELECT 1' >/dev/null 2>&1; then
    admin_user="$candidate"
    admin_is_superuser="$(
      compose exec -T -u postgres z_postgres psql -U "$candidate" -d postgres -tAc \
        "SELECT CASE WHEN rolsuper THEN 'yes' ELSE 'no' END FROM pg_roles WHERE rolname = current_user" 2>/dev/null || true
    )"
    [[ "$admin_is_superuser" == "yes" ]] && break
  fi
done

if [[ -z "$admin_user" ]]; then
  echo "❌ Existing PostgreSQL volume uses an unknown administrator role." >&2
  echo "Restore the previous deploy environment or inspect roles from a database backup." >&2
  echo "The volume was preserved; no data was deleted." >&2
  exit 1
fi

if tcp_login_works "$desired_user" "$desired_password" "$desired_database"; then
  clear_runtime_database_url
  echo "✓ PostgreSQL credentials match deploy/.env (existing data preserved)"
  exit 0
fi

if [[ "$admin_is_superuser" == "yes" ]] && compose exec -T -u postgres \
    -e Z_DESIRED_DB_USER="$desired_user" \
    -e Z_DESIRED_DB_PASSWORD="$desired_password" \
    -e Z_DESIRED_DB_NAME="$desired_database" \
    z_postgres psql -v ON_ERROR_STOP=1 -U "$admin_user" -d postgres >/dev/null <<'SQL'
\getenv desired_user Z_DESIRED_DB_USER
\getenv desired_password Z_DESIRED_DB_PASSWORD
\getenv desired_database Z_DESIRED_DB_NAME

SELECT format(
  'CREATE ROLE %I WITH LOGIN PASSWORD %L',
  :'desired_user',
  :'desired_password'
)
WHERE NOT EXISTS (
  SELECT 1 FROM pg_roles WHERE rolname = :'desired_user'
) \gexec

SELECT format(
  'ALTER ROLE %I WITH LOGIN PASSWORD %L',
  :'desired_user',
  :'desired_password'
) \gexec

SELECT format(
  'ALTER DATABASE %I OWNER TO %I',
  :'desired_database',
  :'desired_user'
)
WHERE EXISTS (
  SELECT 1 FROM pg_database WHERE datname = :'desired_database'
) \gexec
SQL
then
  if tcp_login_works "$desired_user" "$desired_password" "$desired_database"; then
    clear_runtime_database_url
    echo "✓ PostgreSQL credentials match deploy/.env (existing data preserved)"
    exit 0
  fi
fi

if compose exec -T -u postgres \
    -e Z_DESIRED_DB_PASSWORD="$desired_password" \
    z_postgres psql -v ON_ERROR_STOP=1 -U "$desired_user" -d postgres >/dev/null 2>&1 <<'SQL'
\getenv desired_password Z_DESIRED_DB_PASSWORD
ALTER ROLE CURRENT_USER WITH PASSWORD :'desired_password';
SQL
then
  if tcp_login_works "$desired_user" "$desired_password" "$desired_database"; then
    clear_runtime_database_url
    echo "✓ PostgreSQL credentials match deploy/.env (existing data preserved)"
    exit 0
  fi
fi

if [[ "$admin_user" != "$desired_user" ]] && compose exec -T -u postgres \
    -e Z_DESIRED_DB_PASSWORD="$desired_password" \
    z_postgres psql -v ON_ERROR_STOP=1 -U "$admin_user" -d postgres >/dev/null 2>&1 <<'SQL'
\getenv desired_password Z_DESIRED_DB_PASSWORD
ALTER ROLE CURRENT_USER WITH PASSWORD :'desired_password';
SQL
then
  if tcp_login_works "$admin_user" "$desired_password" "$desired_database"; then
    write_runtime_database_url "$admin_user" "$desired_password" "$desired_database"
    echo "✓ PostgreSQL volume uses existing role '$admin_user'; backend runtime was aligned automatically."
    exit 0
  fi
fi

legacy_user=""
legacy_password=""
legacy_database=""
if [[ -f "$legacy_file" && "$legacy_file" != "$ENV_FILE" ]]; then
  legacy_user="$(env_value POSTGRES_USER "$legacy_file")"
  legacy_password="$(env_value POSTGRES_PASSWORD "$legacy_file")"
  legacy_database="$(env_value POSTGRES_DB "$legacy_file")"
fi

if [[ -n "$legacy_user" && -n "$legacy_password" ]]; then
  legacy_database="${legacy_database:-$desired_database}"
  if tcp_login_works "$legacy_user" "$legacy_password" "$legacy_database"; then
    write_runtime_database_url "$legacy_user" "$legacy_password" "$legacy_database"
    echo "✓ PostgreSQL volume uses legacy credentials; backend runtime was aligned automatically."
    exit 0
  fi
fi

echo "❌ PostgreSQL credentials could not be reconciled automatically." >&2
echo "The existing volume does not accept deploy/.env credentials, and no usable legacy credentials were found." >&2
echo "Database data was preserved; no volume was deleted." >&2
exit 3
